version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/go/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - '.:/go/src/thoughts-app'
    tty: true
    stdin_open: true
    depends_on: 
      - db
    links:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - './db-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: app_db
    ports:
      - 5432:5432